In [1]:
import numpy as np 
import pandas as pd 

df = pd.read_csv("Downloads\Sample - Superstore.csv",encoding = "windows-1252")
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [3]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [6]:
# Loop untuk memeriksa setiap kolom yang bertipe data 'object'
for col in df.select_dtypes(include=['object']).columns:
    print(f"=== Kolom: {col} ===")
    print(f"Jumlah Nilai Unik: {df[col].nunique()}")
    
    # Menampilkan 5 nilai unik pertama sebagai sampel pemeriksaan
    print("Sampel Nilai Unik:")
    print(df[col].unique()[:5])
    print("-" * 50)

=== Kolom: Order ID ===
Jumlah Nilai Unik: 5009
Sampel Nilai Unik:
['CA-2016-152156' 'CA-2016-138688' 'US-2015-108966' 'CA-2014-115812'
 'CA-2017-114412']
--------------------------------------------------
=== Kolom: Order Date ===
Jumlah Nilai Unik: 1237
Sampel Nilai Unik:
['11/8/2016' '6/12/2016' '10/11/2015' '6/9/2014' '4/15/2017']
--------------------------------------------------
=== Kolom: Ship Date ===
Jumlah Nilai Unik: 1334
Sampel Nilai Unik:
['11/11/2016' '6/16/2016' '10/18/2015' '6/14/2014' '4/20/2017']
--------------------------------------------------
=== Kolom: Ship Mode ===
Jumlah Nilai Unik: 4
Sampel Nilai Unik:
['Second Class' 'Standard Class' 'First Class' 'Same Day']
--------------------------------------------------
=== Kolom: Customer ID ===
Jumlah Nilai Unik: 793
Sampel Nilai Unik:
['CG-12520' 'DV-13045' 'SO-20335' 'BH-11710' 'AA-10480']
--------------------------------------------------
=== Kolom: Customer Name ===
Jumlah Nilai Unik: 793
Sampel Nilai Unik:
['Claire Gute' 'Darrin Van Huff' "Sean O'Donnell" 'Brosina Hoffman'
 'Andrew Allen']
--------------------------------------------------
=== Kolom: Segment ===
Jumlah Nilai Unik: 3
Sampel Nilai Unik:
['Consumer' 'Corporate' 'Home Office']
--------------------------------------------------
=== Kolom: Country ===
Jumlah Nilai Unik: 1
Sampel Nilai Unik:
['United States']
--------------------------------------------------
=== Kolom: City ===
Jumlah Nilai Unik: 531
Sampel Nilai Unik:
['Henderson' 'Los Angeles' 'Fort Lauderdale' 'Concord' 'Seattle']
--------------------------------------------------
=== Kolom: State ===
Jumlah Nilai Unik: 49
Sampel Nilai Unik:
['Kentucky' 'California' 'Florida' 'North Carolina' 'Washington']
--------------------------------------------------
=== Kolom: Region ===
Jumlah Nilai Unik: 4
Sampel Nilai Unik:
['South' 'West' 'Central' 'East']
--------------------------------------------------
=== Kolom: Product ID ===
Jumlah Nilai Unik: 1862
Sampel Nilai Unik:
['FUR-BO-10001798' 'FUR-CH-10000454' 'OFF-LA-10000240' 'FUR-TA-10000577'
 'OFF-ST-10000760']
--------------------------------------------------
=== Kolom: Category ===
Jumlah Nilai Unik: 3
Sampel Nilai Unik:
['Furniture' 'Office Supplies' 'Technology']
--------------------------------------------------
=== Kolom: Sub-Category ===
Jumlah Nilai Unik: 17
Sampel Nilai Unik:
['Bookcases' 'Chairs' 'Labels' 'Tables' 'Storage']
--------------------------------------------------
=== Kolom: Product Name ===
Jumlah Nilai Unik: 1850
Sampel Nilai Unik:
['Bush Somerset Collection Bookcase'
 'Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back'
 'Self-Adhesive Address Labels for Typewriters by Universal'
 'Bretford CR4500 Series Slim Rectangular Table'
 "Eldon Fold 'N Roll Cart System"]
--------------------------------------------------

In [7]:
# 1. Ubah tipe data ke datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

# 2. Cek apakah ada data yang Ship Date-nya LEBIH KECIL dari Order Date
inkonsisten_tanggal = df[df['Ship Date'] < df['Order Date']]
print(f"Jumlah data tanggal inkonsisten: {len(inkonsisten_tanggal)}")

Jumlah data tanggal inkonsisten: 0

In [8]:
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [13]:
# Cek ringkasan statistik (perhatikan nilai 'min' untuk Sales dan Quantity)
df[['Sales', 'Quantity', 'Profit']].describe()

# Atau filter langsung untuk melihat data yang tidak masuk akal
inkonsisten_sales = df[df['Sales'] <= 0]
inkonsisten_qty = df[df['Quantity'] <= 0]

print("=== HASIL CEK INKONSISTEN SALES ===")
print (inkonsisten_sales)
print("\n" + "="*50 + "\n")
print("=== HASIL CEK INKONSISTEN QTY ===")
print (inkonsisten_qty)

=== HASIL CEK INKONSISTEN SALES ===
Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

==================================================

=== HASIL CEK INKONSISTEN QTY ===
Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [15]:
# Menghitung batas atas untuk Outlier Sales
Q1 = df['Sales'].quantile(0.25)
Q3 = df['Sales'].quantile(0.75)
IQR = Q3 - Q1
batas_atas = Q3 + 1.5 * IQR

# Filter untuk melihat data yang nilainya di luar kewajaran
outlier_sales = df[df['Sales'] > batas_atas]

print(f"Batas atas penjualan normal: {batas_atas}")
print(f"Jumlah data outlier (sangat tinggi): {len(outlier_sales)}")
print("\n" + "="*50 + "\n")
print("Sampel data outlier:")
outlier_sales[['Customer Name', 'Product Name', 'Sales', 'Quantity', 'Profit']].head()

Batas atas penjualan normal: 498.93
Jumlah data outlier (sangat tinggi): 1167

==================================================

Sampel data outlier:

,Customer Name,Product Name,Sales,Quantity,Profit
1,Claire Gute,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,219.5820
3,Sean O'Donnell,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,-383.0310
7,Brosina Hoffman,Mitel 5320 IP Phone VoIP phone,907.1520,6,90.7152
10,Brosina Hoffman,Chromcraft Rectangular Conference Tables,1706.1840,9,85.3092
11,Brosina Hoffman,Konftel 250 Conference phone - Charcoal black,911.4240,4,68.3568

In [17]:
# Menghitung batas atas untuk Outlier Quantity
Q1 = df['Quantity'].quantile(0.25)
Q3 = df['Quantity'].quantile(0.75)
IQR = Q3 - Q1
batas_atas = Q3 + 1.5 * IQR

# Filter untuk melihat data yang nilainya di luar kewajaran
outlier_quantity = df[df['Quantity'] > batas_atas]

print(f"Batas atas penjualan normal: {batas_atas}")
print(f"Jumlah data outlier (sangat tinggi): {len(outlier_sales)}")
print("\n" + "="*50 + "\n")
print("Sampel data outlier:")
outlier_quantity[['Customer Name', 'Product Name', 'Sales', 'Quantity', 'Profit']].head()

Batas atas penjualan normal: 9.5
Jumlah data outlier (sangat tinggi): 170

==================================================

Sampel data outlier:

,Customer Name,Product Name,Sales,Quantity,Profit
113,Ryan Crowe,"OIC Colored Binder Clips, Assorted Sizes",40.096,14,14.5348
139,Lena Creighton,Longer-Life Soft White Bulbs,43.120,14,20.6976
147,Justin Ellison,Plantronics Cordless Phone Headset with In-lin...,384.450,11,103.8015
251,Kelly Collister,Logitech P710e Mobile Speakerphone,3347.370,13,636.0003
329,Patrick O'Brill,Round Specialty Laser Printer Labels,100.240,10,33.8310

In [18]:
# Menghitung batas atas untuk Outlier Profit
Q1 = df['Profit'].quantile(0.25)
Q3 = df['Profit'].quantile(0.75)
IQR = Q3 - Q1
batas_atas = Q3 + 1.5 * IQR

# Filter untuk melihat data yang nilainya di luar kewajaran
outlier_profit = df[df['Profit'] > batas_atas]

print(f"Batas atas penjualan normal: {batas_atas}")
print(f"Jumlah data outlier (sangat tinggi): {len(outlier_sales)}")
print("\n" + "="*50 + "\n")
print("Sampel data outlier:")
outlier_profit[['Customer Name', 'Product Name', 'Sales', 'Quantity', 'Profit']].head()

Batas atas penjualan normal: 70.816875
Jumlah data outlier (sangat tinggi): 170

==================================================

Sampel data outlier:

,Customer Name,Product Name,Sales,Quantity,Profit
1,Claire Gute,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,219.5820
7,Brosina Hoffman,Mitel 5320 IP Phone VoIP phone,907.152,6,90.7152
10,Brosina Hoffman,Chromcraft Rectangular Conference Tables,1706.184,9,85.3092
13,Irene Maddox,Fellowes PB200 Plastic Comb Binding Machine,407.976,3,132.5922
24,Emily Burns,Bretford CR4500 Series Slim Rectangular Table,1044.630,3,240.2649

In [11]:
# Cek rata-rata profit berdasarkan besaran diskon
analisis_diskon = df.groupby('Discount')['Profit'].mean().reset_index()

print("=== RATA-RATA PROFIT BERDASARKAN DISKON ===")
print(analisis_diskon)

=== RATA-RATA PROFIT BERDASARKAN DISKON ===
    Discount      Profit
0       0.00   66.900292
1       0.10   96.055074
2       0.15   27.288298
3       0.20   24.702572
4       0.30  -45.679636
5       0.32  -88.560656
6       0.40 -111.927429
7       0.45 -226.646464
8       0.50 -310.703456
9       0.60  -43.077212
10      0.70  -95.874060
11      0.80 -101.796797

In [12]:
# Menyimpan DataFrame yang sudah bersih ke file CSV baru
df.to_csv('Downloads\superstore_clean.csv', index=False)

print("Selesai! File 'superstore_clean.csv' sudah siap dimasukkan ke Tableau.")

Selesai! File 'superstore_clean.csv' sudah siap dimasukkan ke Tableau.